### PR TITLE
Remove font tags from some namespaces on save 

### PR DESCRIPTION
**Pull request by superdav42**
#243
#63

### CODE REVIEW

**Comment by jag3773** [comment]
@superdav42 can we modify this to remove the font tags from everything?  We don't want them anywhere.

**Comment by superdav42** [comment]
@jag3773 We can, but #243 said only do it on these namespaces. &lt;font&gt; tags are used by the ckgedit plugin under normal circumstances so if we always remove them certain features won't work, like all the font styling features. 
see https://www.dokuwiki.org/plugin:ckgedit:font_styling

**Comment by jag3773** [comment]
Understood, we don't want the <font> junk anywhere.

**Comment by superdav42** [comment]
@jag3773 Alright, Updated to remove font tags everywhere.

**Comment by superdav42** [comment]
Also included is update to tag plugin which searches multiple namespaces or excludes namespaces.
The tag plugin is a fork in my repo.

**Comment by richmahn** [comment]
@jag3773 Is this good to go?

**Comment by richmahn** [comment]
@superdav42 I see you changed the URI for this repo in the .gitmodules file. Will this have no problem in updating a running copy that has the dokufreak/tag repo to your repo? This needs to be tested.

**Comment by superdav42** [comment]
@richmahn I'm not sure I haven't worked with submodules enough. 
I could make this PR to a different branch if you want to test it. Someone else will have to create the branch on unfoldingWord-dev/Door43 since i don't have write access. That'd be the easiest way to test it I think.

**Comment by jag3773** [comment]
Yes regarding the font tag issue.

**Comment by richmahn** [comment]
going to merge this. I will work on the change of URI for the submodule to make sure it switches over easily.

**Pull request merged**
