### PR TITLE
updated hook for running git merge tool indexing

### PR DESCRIPTION
**Pull request by da1nerd**

### CODE REVIEW

**Comment by da1nerd** [comment]
forgot to merge in updates from upstream

**Comment by alerque** [comment]
@neutrinog You know you can update the contents of a PR without having to close it and open a new one right?

**Comment by da1nerd** [comment]
haha I only just found that out :)

**Comment by alerque** [comment]
So ya ;-) I guess you got it but PR's are proposals to merge a specific branch into another branch—and they are always for the current states of those branches. A lot of times the mis-conception is that it's a fixed snapshot of patches at the time it was proposed but actually the moment it's merged is more important than the proposal. Because it's actually a thin wrapper around normal git branching operations it's actually quite dynamic. You can add new commits or even edit and remove existing ones (via rebase) by continuing to work on the branch (and force pushing if you need to remove commits or rebase anything). It isn't frozen until it's merged.

**Pull request closed without merging**
