### PR TITLE
add HELP to site-tools

### PR DESCRIPTION
**Pull request by Aarontse**

### CODE REVIEW

**Comment by Aarontse** [comment]
1. The area which the new HELP (button-link) added to is call site-tools.
2. Modified /var/www/Door43/lib/tpl/door43/tpl_header.php To add a new item in site-tools, in this case [HELP]. (search for HELP in that file the see where to add)
3. Modified the lang.php for display of the item in English.
4. Modified the inc/tempate.php to handle the flow of HELP item.
5. Modified the inc/actions.php to define the action, now it hardcode as follow:
   
   ```
    act_redirect('en/obs/help',$preact);
   ```

**Comment by alerque** [comment]
Why do we have two PR's for this? #315 into the development branch should be the correct one, feature branches should not get directly merged to master like this. Once a feature is merged to the dev branch and tested, it can then be merged to master from there. All feature work such as this should be based on the dev branch as you appear to have done already in the first PR.

**Comment by richmahn** [comment]
@alerque: I'll work with @Aarontse at making sure he develops and does a PR with the development branch. Thanks for noticing.

**Comment by phillip-hopper** [comment]
@richmahn Should this PR be closed?

**Comment by alerque** [comment]
I don't think this is resolved yet. I still have a tab open meaning to reply to the related discussion in #315. But I haven't reviewed anything @richmahn may have done directly with the OP.

**Pull request closed without merging**
