### PR TITLE
Add HELP to site-tools

### PR DESCRIPTION
**Pull request by Aarontse**

### CODE REVIEW

**Comment by Aarontse** [comment]
1. The area which the new HELP (button-link) added to is call site-tools.
2. Modified /var/www/Door43/lib/tpl/door43/tpl_header.php To add a new item in site-tools, in this case [HELP]. (search for HELP in that file the see where to add)
3. Modified the lang.php for display of the item in English.
4. Modified the inc/tempate.php to handle the flow of HELP item.
5. Modified the inc/actions.php to define the action, now it hardcode as follow:
   
   ```
    act_redirect('en/obs/help',$preact);
   ```

**Comment by alerque** [comment]
A couple comments:
- I'm not sure why this didn't pass the unit checks. Did you look at the error from Travis and does it make any sense to you? Perhaps someone with more hands on with this code than I might recognize what's up there.
- Commit ea04fac needs to be dropped because it's going to cause conflicts later. The feature branch doesn't actually need to mess with that plugin so it should only change files that are relevant to the change being made. In this case that merge commit is going to cause a conflict if the submodule is changed again at any point and it will not merge cleanly.
- Are all the commits with the same commit message really doing the same thing? If there is only one main action going on here can we just squash them all into one commit with the same message? Or if there is more than one logical change being made can we get log messages that say what's happening in each?

A `git rebase` will be able to solve both of the latter issues and clean this up. If you are not aware of how to do this let me know what git client you are using and I will send exact instructions, or if that's all to confusing at least answer the questions and I can run the rebase for you and give you a drop in replacement branch.

**Comment by Aarontse** [comment]
Hi Caleb,

Thanks for your help on the issues.

Yes I did Pull more than once for the same set of code. The first time, I
got error after the pull, I have no idea if it got through or not, so I
pull it again, I did try to delete the first pull but not sure how, and I
was not sure if CLOSE mean Delete.....  Sorry for the confusion and I will
be more careful.

About the error, I have no idea....

mostly I am using command line git on ubuntu with the web site
www.github.com to handle the project.

No, I am not aware about git rebase, so far I am just kind of marginally
learn what I need, so yes, please go ahead and fix it for me, thanks in
advance. Also do send me instructions on it if its not too much trouble.
And I will read more about the git.

Thanks again for your help and may God keep and guide us.

Aaron

**Comment by phillip-hopper** [comment]
@Aarontse This pull request either needs to be closed or fixed so that the tests pass.

**Pull request closed without merging**
